#!/bin/bash

if [ -L "$0" ]; then
    root=$(cd "$(dirname "$(readlink "$0")")" && pwd)
else
    root=$(cd "$(dirname "$0")" && pwd)
fi

TAG="rybnico/octodns-kubernetes"

set -x

# Does it have my executables handy in $PATH?
docker run --rm "$TAG" which \
	  octodns-compare \
	  octodns-dump \
	  octodns-report \
	  octodns-sync \
	  octodns-validate

# Execute one.
docker run --rm "$TAG" \
	  octodns-sync --help
